<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2000/REC-xhtml1-20000126/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="[% root %]css/global.css" />
    [%# <link rel="shortcut icon" href="img/favicon.png" />  %]
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="ROBOTS" content="ALL" />
    <title>[% title %]</title>
  </head>
  <body>

      
      <div class="pagetitle">
      <a href="[% root %]"><img src="[% root %]graphics/twinslogo7.gif" height=140 alt="Edinburgh and Lothians Twin Club" /></a><hr>
      </div>
