<div id="footer">
	[% SET showibm = 0; IF showibm == 1 %]
		<a href="http://egee-intranet.web.cern.ch/egee-intranet/gateway.html"><img src="graphics/EGEElogo.jpg" alt="EGEE" /></a>&nbsp;&nbsp;&nbsp;<a href="http://www.ibm.com/"><img src="graphics/ibmlogohome.gif" alt="IBM" /></a><br />
	[% END %]
    
	<img src="[% root %]graphics/scotgridsmall.png" alt="ScotGrid Logo" /><br />
	<a href="http://www.gridpp.ac.uk">A member of GridPP</a>
	<hr />
	<a href="http://validator.w3.org/check/referer">Valid XHTML 1.0 Strict</a> | 
	<a href="http://jigsaw.w3.org/css-validator/">Valid CSS</a>
	<div style="margin-top:2ex;color:gray">
	Original design by Fraser Speirs. Current maintainer Graeme Stewart.
	</div>
</div>
  </body>
</html>
