<div id="nav">
      <div class="button"></div>
      <div id="links" class="menu">
        <div class="title">On <a href="[% root || '.' %]">Edinburgh Twins Club</a></div>
        <div class="menucontent">
          <ul class="makeMenu">
            <li>
              <a class="ulheading" href="[% root %]aboutus/">About Us</a>
                <ul>
                  <li><a class="ulheading" href="[% root %]aboutus/howitstarted">How it started</a></li>
                  <li><a class="ulheading" href="[% root %]aboutus/committee">Committee</a></li>
                </ul>
              <div>What is the ETC?</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]groups/">Groups</a>
                 <ul>
                  <li><a class="ulheading" href="[% root %]groups/map">Map</a></li>
                 </ul>
              <div>Babies, Bumps &amp; Toddler Groups</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]events/">Events</a>
              <div>Social Events for twins and their parents?</div>
                 <ul>
                  <li><a class="ulheading" href="[% root %]events/map">Map</a></li>
                 </ul>
            </li>
            <li>
              <a class="ulheading" href="[% root %]messageboard.php">Messageboard</a>
              <div>Chat with other twin mums and dads</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]triplets/">Triplets</a>
              <div>Information for parents and carers of triplets</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]tips/">Tips</a>
                <ul>
                  <li><a class="ulheading" href="[% root %]tips/feeding">Feeding</a></li>
                  <li><a class="ulheading" href="[% root %]tips/outabout">Out and About</a></li>
                  <li><a class="ulheading" href="[% root %]tips/prams">Prams</a></li>
                  <li><a class="ulheading" href="[% root %]tips/general">General</a></li>
                  <li><a class="ulheading" href="[% root %]tips/goodbuys">Good Buys</a></li>
                </ul>
              <div>Useful tips on how to cope with new twins</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]join">Join</a>
              <div>Lots of benefits for only &pound;12 a year</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]recommended">Recommended</a>                <ul>
                  <li><a class="ulheading" href="[% root %]recommended/pregnancy">Pregnancy</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/baby">Baby</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/toddler">Toddler</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/child">Child</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/feeding">Feeding</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/booksforchildren">Books For Children</a></li>
                  <li><a class="ulheading" href="[% root %]recommended/general">General</a></li>
                </ul>              <div>Useful Books</div>
            </li>
            <!-- <li>
              <a class="ulheading" href="[% root %]members">Members</a>
                <ul>
                  <li><a class="ulheading" href="[% root %]members/newsletters">Newsletters</a></li>
                  <li><a class="ulheading" href="[% root %]members/discounts">Discounts</a></li>
                </ul>
              <div>Members Only Area</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]committee">Committee</a>
                <ul>
                  <li><a class="ulheading" href="[% root %]committee/constitution">Constitution</a></li>
                  <li><a class="ulheading" href="[% root %]committee/minutes">Minutes</a></li>
                  <li><a class="ulheading" href="[% root %]committee/reports">Reports</a></li>
                </ul>
              <div>Committee Members Only Area</div>
            </li> -->
            <li>
              <a class="ulheading" href="[% root %]links">Links</a>
              <div>Some twin related links</div>
            </li>
            <li>
              <a class="ulheading" href="[% root %]contacts/">Contacts</a>
              <div>Any questions? Drop us an email...</div>
            </li>
          </ul>
<iframe style="margin: 0 auto; border: 0; width: 120px; height: 90px;" src="http://rcm-uk.amazon.co.uk/e/cm?t=edinburghtwin-21&amp;o=2&amp;p=20&amp;l=qs1&amp;f=ifr" scrolling="no"></iframe>
        </div>
      </div>
</div>
