<div id="nav">
      <div class="button">
      </div>
      <div id="links" class="menu">
        <div class="title">On <a href="<? echo "$root"; ?>">Edinburgh Twins Club</a></div>
        <div class="menucontent">
          <ul class="makeMenu">
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>aboutus/">About Us</a>
                <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>aboutus/howitstarted">How it started</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>aboutus/committee">Committee</a></li>
                </ul>
              <div>What is the ETC?</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>groups/">Groups</a>
                 <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>groups/map">Map</a></li>
                 </ul>
              <div>Babies, Bumps & Toddler Groups</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>events/">Events</a>
              <div>Social Events for twins and their parents?</div>
                 <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>events/map">Map</a></li>
                 </ul>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>../messageboard.php">Messageboard</a>
              <div>Chat with other twin mums and dads</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>../../triplets/">Triplets</a>
              <div>Information for parents and carers of triplets</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>tips/">Tips</a>
                <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>tips/feeding">Feeding</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>tips/outabout">Out and About</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>tips/prams">Prams</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>tips/general">General</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>tips/goodbuys">Good Buys</a></li>
                </ul>
              <div>Useful tips on how to cope with new twins</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>join">Join</a>
              <div>Lots of benefits for only &pound;10 a year</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>recommended">Recommended</a>                <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/pregnancy">Pregnancy</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/baby">Baby</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/toddler">Toddler</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/child">Child</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/feeding">Feeding</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/booksforchildren">Books For Children</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>recommended/general">General</a></li>
                </ul>              <div>Useful Books</div>
            </li>
            <!-- <li>
              <a class="ulheading" href="<? echo "$root"; ?>members">Members</a>
                <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>members/newsletters">Newsletters</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>members/discounts">Discounts</a></li>
                </ul>
              <div>Members Only Area</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>committee">Committee</a>
                <ul>
                  <li><a class="ulheading" href="<? echo "$root"; ?>committee/constitution">Constitution</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>committee/minutes">Minutes</a></li>
                  <li><a class="ulheading" href="<? echo "$root"; ?>committee/reports">Reports</a></li>
                </ul>
              <div>Committee Members Only Area</div>
            </li> -->
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>links">Links</a>
              <div>Some twin related links</div>
            </li>
            <li>
              <a class="ulheading" href="<? echo "$root"; ?>contacts/">Contacts</a>
              <div>Any questions? Drop us an email...</div>
            </li>
          </ul>
<center><iframe src="http://rcm-uk.amazon.co.uk/e/cm?t=edinburghtwin-21&o=2&p=20&l=qs1&f=ifr" width="120" height="90" frameborder="0" scrolling="no"></iframe></center>
        </div>
      </div>
